poll/urls.py
from django.conf.urls import url
from .views import (
    PollCreateView,
    PollDetailView,
    PollUpdateView,
    QuestionCreateView
)


urlpatterns = [
    url(r'^(?P<pk>\d+)/$', PollUpdateView.as_view(), name='poll_update'),
    url(r'^(?P<pk>\d+)/questions/$', QuestionCreateView.as_view(), name='question_create'),
    url(r'^detail/(?P<pk>\d+)/$', PollDetailView.as_view(), name='poll_detail'),
    url(r'^create/$', PollCreateView.as_view(), name='poll_create'),
]

src/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from poll import urls as poll_urls

urlpatterns = [
    url(r'^polls/', include(poll_urls)),
    url(r'^admin/', admin.site.urls),
]

poll/models.py
from django.contrib.auth.models import User
from django.db import models


class Anonymous(models.Model):
    hash = models.CharField(max_length=32, unique=True)

    def __str__(self):
        return self.hash


class Poll(models.Model):
    PERMS = (
        ('not_auth', 'Not authenticated'),
        ('auth', 'Authenticated'),
        ('confirmed_email', 'Confirmed email')
    )
    title = models.CharField(max_length=120)
    description = models.TextField()
    permission = models.CharField(max_length=16, choices=PERMS)

    def get_absolute_url(self):
        return '/polls/%i/' % self.id

    def get_detail_url(self):
        return '/polls/detail/%i' % self.id


class Question(models.Model):
    INPUT_TYPES = (
        ('TXT', 'text'),
        ('RAD', 'radio'),
        ('CHK', 'checkbox'),
        ('SLT', 'select'),
        ('MSL', 'multiselect'),
        ('NUM', 'number'),
        ('EMP', '')
    )
    poll = models.ForeignKey(Poll)
    text = models.CharField(max_length=255)
    type = models.CharField(
        max_length=3, choices=INPUT_TYPES,
        default='EMP', verbose_name='Answer type'
    )
    size = models.IntegerField(default=1)
    voted_users = models.ManyToManyField(User)
    voted_anonymous = models.ManyToManyField(Anonymous)


class Answer(models.Model):
    question = models.ForeignKey(Question)
    text = models.CharField(max_length=120)
    votes = models.IntegerField(default=0)
    max_value = models.IntegerField(blank=True, null=True)
    min_value = models.IntegerField(blank=True, null=True)


class UserAgent(models.Model):
    data = models.TextField()

poll/forms.py
from django.forms import ModelForm, NumberInput
from .models import Poll, Question, Answer


class PollModelForm(ModelForm):
    class Meta:
        model = Poll
        fields = ['title', 'description', 'permission']


class QuestionModelForm(ModelForm):
    class Meta:
        model = Question
        fields = ['text', 'type', 'size']
        widgets = {
            'size': NumberInput(attrs={'min': 1, 'max': 10})
        }


class AnswerModelForm(ModelForm):
    class Meta:
        model = Answer
        fields = ['text', 'max_value', 'min_value']

poll/views.py
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ValidationError
from django.db import transaction
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.views.generic import CreateView, DetailView, UpdateView

from .models import Poll, Question, UserAgent, Anonymous
from .forms import PollModelForm, QuestionModelForm, AnswerModelForm


class JSONResponseMixin:

    def render_to_json_response(self, context, **response_kwargs):
        return JsonResponse(
            context,
            safe=False,
            **response_kwargs
        )


class PollCreateView(CreateView):
    model = Poll
    form_class = PollModelForm
    template_name = 'poll_create.html'

    def post(self, request, *args, **kwargs):
        response = super(PollCreateView, self).post(request, *args, **kwargs)
        content_type = ContentType.objects.get_for_model(Poll)
        Permission.objects.create(
            codename=self.object.permission,
            name=self.object.get_permission_display(),
            content_type=content_type,
        )
        return response


class QuestionCreateView(JSONResponseMixin, CreateView):
    model = Question
    form_class = QuestionModelForm
    template_name = 'question_create.html'
    success_url = '/create/'

    def post(self, request, *args, **kwargs):
        errors = {}
        form = self.get_form()
        try:
            with transaction.atomic():
                if form.is_valid():
                    self.object = form.save(commit=False)
                    self.object.poll_id = self.kwargs.get(self.pk_url_kwarg)
                    self.object.save()
                else:
                    for key, value in form.errors.as_data().items():
                        errors[key] = value[0].message

                for key, value in request.POST.items():
                    if 'choice' in key:
                        max_value = request.POST.get('max_value', None)
                        min_value = request.POST.get('min_value', None)
                        answer_form = AnswerModelForm({
                            'text': value, 'max_value': max_value,
                            'min_value': min_value
                        })
                        if answer_form.is_valid() and self.object:
                            answer = answer_form.save(commit=False)
                            answer.question = self.object
                            answer.save()
                        else:
                            for _, value in answer_form.errors.as_data().items():
                                errors[key] = value[0].message
                if errors:
                    raise ValidationError('')
                else:
                    return self.render_to_json_response({'msg': 'success'})
        except ValidationError:
            return self.render_to_json_response(errors, status=400)


class PollDetailView(DetailView):
    template_name = 'poll_detail.html'
    model = Poll


class PollUpdateView(JSONResponseMixin, UpdateView):
    model = Poll
    template_name = 'poll_update.html'
    form_class = PollModelForm
    template_name_suffix = 'poll'
    success_url = '/polls/'

    def post(self, request, *args, **kwargs):
        for key, value in request.POST.items():
            if 'question' in key and value:
                _, question_id = key.split('_')
                question = Question.objects.get(id=question_id)
                if request.user.is_authenticated():
                    user = request.user
                    if question.voted_users.filter(id=user.id).exists():
                        context = {'error': 'your answers cannot be accepted because you are already answered'}
                        return self.render_to_response(context=context)
                    else:
                        question.voted_users.add(user)
                else:
                    hash_ = request.POST.get('hashed_ip')
                    anonym, _ = Anonymous.objects.get_or_create(hash=hash_)
                    if question.voted_anonymous.filter(hash=hash_).exists():
                        context = {'error': 'your answers cannot be accepted because you are already answered'}
                        return self.render_to_response(context=context)
                    else:
                        question.voted_anonymous.add(anonym)

                if question.type == 'TXT' or question.type == 'NUM':
                    question.answer_set.create(text=value)
                else:
                    answer = question.answer_set.get(id=value)
                    answer.votes += 1
                    answer.save()
        UserAgent.objects.create(date=request.META['HTTP_USER_AGENT'])
        self.object = self.get_object()
        return HttpResponseRedirect(self.object.get_detail_url())

poll/templates/poll_create.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <h3>Create poll</h3>
    <form method="post" id="form" action={% url 'poll_create' %}>
        {% csrf_token %}
        <p>
            {{ form.title.label_tag }}
            {{ form.title }}
        </p>
        <p>{{ form.description.label_tag }}</p>
        <p>{{ form.description }}</p>
        <p>
            {{ form.permission.label_tag }}
            {{ form.permission }}
        </p>
        <div>
            <input type="submit" value="Create">
        </div>
    </form>
{% endblock %}

{% block javascript %}{% endblock %}

poll/templates/poll_detail.html
{% extends 'base.html' %}

{% block content %}
    <h3>Poll results</h3>
    <h4>{{ poll.title }}</h4>
    <p>{{ poll.description }}</p>
    <div>
        <ol>
            {% for question in poll.question_set.all %}
                <li>{{ question.text }}</li>
                {% if question.voted_users.all %}
                    users:
                    {% for user in question.voted_users.all %}
                        {{ user }}
                    {% endfor %}
                {% endif %}
                <br>
                {% if question.voted_anonymous.all %}
                    anon: {{ question.voted_anonymous.all|length }}
                {% endif %}
                <br>
                {% if question.type == 'TXT' %}
                    {% for answer in question.answer_set.all %}
                        {{ answer.text }}
                        <hr>
                    {% endfor %}
                {% else %}
                    {% for answer in question.answer_set.all %}
                        text: {{ answer.text }}<br>
                        votes: {{ answer.votes }}
                        <hr>
                    {% endfor %}
                {% endif %}


{#                {% if question.type == 'SLT' %}#}
{#                    <select name="question_{{ question.id }}" id="">#}
{#                {% elif question.type == 'MSL' %}#}
{#                    <select name="question_{{ question.id }}" id="" multiple size="{{ question.size }}">#}
{#                {% elif question.type == 'RAD' %}#}
{#                    <ul>#}
{#                {% endif %}#}
{##}
{#                {% if question.type == 'SLT' or question.type == 'MSL' %}#}
{#                    {% for answer in question.answer_set.all %}#}
{#                        <option value="{{ answer.id }}">{{ answer.text }}</option>#}
{#                    {% endfor %}#}
{#                {% elif question.type == 'TXT' %}#}
{#                    {% for answer in question.answer_set.all %}#}
{#                        <p>{{ answer.text }}{{ answer }}</p>#}
{#                    {% endfor %}#}
{##}
{#                {% elif question.type == 'RAD' %}#}
{#                    {% for answer in question.answer_set.all %}#}
{#                        <li><input type="radio" name="question_{{ question.id }}" value="{{ answer.id }}"><label for="">{{ answer.text }}</label></li>#}
{#                    {% endfor %}#}
{#                {% elif question.type == 'CHK' %}#}
{#                    {% for answer in question.answer_set.all %}#}
{#                        <input type="checkbox" name="question_{{ question.id }}" value="{{ answer.id }}"><label for="">{{ answer.text }}</label>#}
{#                    {% endfor %}#}
{#                {% elif question.type == 'NUM' %}#}
{#                    {% with question.answer_set.first as answer %}#}
{#                        <input type="number" name="question_{{ question.id }}" max="{{ answer.max_value }}" min="{{ answer.min_value }}" value="{{ answer.text }}">#}
{#                    {% endwith %}#}
{#                {% endif %}#}

            {% if question.type == 'SLT' or question.type == 'MSL' %}
                </select>
            {% elif question.type == 'RAD' %}
                </ul>
            {% endif %}
            {% endfor %}
        </ol>
    </div>


{% endblock %}

poll/templates/poll_update.html
{% extends 'base.html' %}

{% block content %}
    <h3>Poll</h3>
    {{ user }}
    {% if error %}
        {{ error }}
    {% else %}
    <form method="post">{% csrf_token %}
        <div>
            <h2>{{ poll.title }}</h2>
            <p>{{ poll.description }}</p>
        </div>
        <div>
            <ol>
                {% for question in poll.question_set.all %}
                    <li>{{ question.text }}</li>
                    {% if question.type == 'SLT' %}
                        <select name="question_{{ question.id }}" id="">
                    {% elif question.type == 'MSL' %}
                        <select name="question_{{ question.id }}" id="" multiple size="{{ question.size }}">
                    {% elif question.type == 'RAD' %}
                        <ul>
                    {% endif %}

                    {% if question.type == 'SLT' or question.type == 'MSL' %}
                        {% for answer in question.answer_set.all %}
                            <option value="{{ answer.id }}">{{ answer.text }}</option>
                        {% endfor %}
                    {% elif question.type == 'TXT' %}
                        {% with question.answer_set.first as answer %}
                            <input type="text" name="question_{{ question.id }}" placeholder="{{ answer.text }}">
                        {% endwith %}
                    {% elif question.type == 'RAD' %}
                        {% for answer in question.answer_set.all %}
                            <li><input type="radio" name="question_{{ question.id }}" value="{{ answer.id }}"><label for="">{{ answer.text }}</label></li>
                        {% endfor %}
                    {% elif question.type == 'CHK' %}
                        {% for answer in question.answer_set.all %}
                            <input type="checkbox" name="question_{{ question.id }}" value="{{ answer.id }}"><label for="">{{ answer.text }}</label>
                        {% endfor %}
                    {% elif question.type == 'NUM' %}
                        {% with question.answer_set.first as answer %}
                            <input type="number" name="question_{{ question.id }}" max="{{ answer.max_value }}" min="{{ answer.min_value }}" value="{{ answer.text }}">
                        {% endwith %}
                    {% endif %}

                    {% if question.type == 'SLT' or question.type == 'MSL' %}
                        </select>
                    {% elif question.type == 'RAD' %}
                        </ul>
                    {% endif %}
                {% endfor %}
            </ol>
        </div>
        <input type="submit" value="Submit">
    </form>
    {% endif %}
{% endblock %}

poll/templates/question_create.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <h3>Create question</h3>
    <form method="post" id="form">
        {% csrf_token %}
        {{ form.as_p }}
        <div id="choices"></div>
        <div id="button"></div>
        <div>
            <input id="create_button" type="submit" value="Create">
        </div>

    </form>
{% endblock %}

{% block javascript %}
    <script src={% static 'poll/js/create_question_form.js' %}></script>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'poll/css/styles.css' %}">
</head>
<body>

<div class="contante">
    {% block content %}{% endblock %}
</div>
    <script src={% static 'poll/js/jquery-1.12.4.min.js' %}></script>
    {% block javascript %}{% endblock %}

</body>
</html>